var searchData=
[
  ['game',['Game',['../class_elo_buddy_1_1_game.html',1,'EloBuddy']]],
  ['gameafkeventargs',['GameAfkEventArgs',['../class_elo_buddy_1_1_game_afk_event_args.html',1,'EloBuddy']]],
  ['gamebugsplateventargs',['GameBugSplatEventArgs',['../class_elo_buddy_1_1_game_bug_splat_event_args.html',1,'EloBuddy']]],
  ['gameendeventargs',['GameEndEventArgs',['../class_elo_buddy_1_1_game_end_event_args.html',1,'EloBuddy']]],
  ['gamenotifyeventargs',['GameNotifyEventArgs',['../class_elo_buddy_1_1_game_notify_event_args.html',1,'EloBuddy']]],
  ['gameobject',['GameObject',['../class_elo_buddy_1_1_game_object.html',1,'EloBuddy']]],
  ['gameobjectcreateeventargs',['GameObjectCreateEventArgs',['../class_elo_buddy_1_1_game_object_create_event_args.html',1,'EloBuddy']]],
  ['gameobjectfloatpropertychangeeventargs',['GameObjectFloatPropertyChangeEventArgs',['../class_elo_buddy_1_1_game_object_float_property_change_event_args.html',1,'EloBuddy']]],
  ['gameobjectintegerpropertychangeeventargs',['GameObjectIntegerPropertyChangeEventArgs',['../class_elo_buddy_1_1_game_object_integer_property_change_event_args.html',1,'EloBuddy']]],
  ['gameobjectnewpatheventargs',['GameObjectNewPathEventArgs',['../class_elo_buddy_1_1_game_object_new_path_event_args.html',1,'EloBuddy']]],
  ['gameobjectnotfoundexception',['GameObjectNotFoundException',['../class_elo_buddy_1_1_game_object_not_found_exception.html',1,'EloBuddy']]],
  ['gameobjectplayanimationeventargs',['GameObjectPlayAnimationEventArgs',['../class_elo_buddy_1_1_game_object_play_animation_event_args.html',1,'EloBuddy']]],
  ['gameobjectprocessspellcasteventargs',['GameObjectProcessSpellCastEventArgs',['../class_elo_buddy_1_1_game_object_process_spell_cast_event_args.html',1,'EloBuddy']]],
  ['gameobjectteleporteventargs',['GameObjectTeleportEventArgs',['../class_elo_buddy_1_1_game_object_teleport_event_args.html',1,'EloBuddy']]],
  ['gamepacketeventargs',['GamePacketEventArgs',['../class_elo_buddy_1_1_game_packet_event_args.html',1,'EloBuddy']]],
  ['gamestarteventargs',['GameStartEventArgs',['../class_elo_buddy_1_1_game_start_event_args.html',1,'EloBuddy']]],
  ['gameupdateeventargs',['GameUpdateEventArgs',['../class_elo_buddy_1_1_game_update_event_args.html',1,'EloBuddy']]],
  ['geometry',['Geometry',['../class_elo_buddy_1_1_s_d_k_1_1_geometry.html',1,'EloBuddy::SDK']]],
  ['getautoattackrange',['GetAutoAttackRange',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#aa62ca3b28c3851e286965696caa58915',1,'EloBuddy::SDK::Extensions']]],
  ['getbestconecastposition',['GetBestConeCastPosition',['../class_elo_buddy_1_1_s_d_k_1_1_spell_1_1_skillshot.html#afc013f39eb98fb18c4953ff31962cbda',1,'EloBuddy::SDK::Spell::Skillshot']]],
  ['getcollisionflags',['GetCollisionFlags',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#a3ee8abad3ec8c29f2332bb8920574006',1,'EloBuddy.SDK.Extensions.GetCollisionFlags(this Vector2 vector)'],['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#ade4dd52313f3ff593d63d059cfee8f8d',1,'EloBuddy.SDK.Extensions.GetCollisionFlags(this Vector3 vector)']]],
  ['getcollisionpoint',['GetCollisionPoint',['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_position_1_1_collision.html#ae4bf9299516c2c4417788c93eb11102a',1,'EloBuddy::SDK::Prediction::Position::Collision']]],
  ['gethighestspellrange',['GetHighestSpellRange',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#af36c72931e98e6b03fdecaec263d3d8b',1,'EloBuddy::SDK::Extensions']]],
  ['getitemslot',['GetItemSlot',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#a42ffa74c2b9ad4865ab1e8fc3c145fd3',1,'EloBuddy.SDK.Extensions.GetItemSlot(this IEnumerable&lt; InventorySlot &gt; inventory, params int[] itemIds)'],['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#a6d9cc69adaba6b2acc200ae3d5b343e9',1,'EloBuddy.SDK.Extensions.GetItemSlot(this IEnumerable&lt; InventorySlot &gt; inventory, params ItemId[] items)'],['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#ad0d9d3cb542faa16c3f0bc347d03f603',1,'EloBuddy.SDK.Extensions.GetItemSlot(this Obj_AI_Base target, params int[] itemIds)'],['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#a8c27a22378888894342c73566f6499cf',1,'EloBuddy.SDK.Extensions.GetItemSlot(this Obj_AI_Base target, params ItemId[] itemIds)']]],
  ['getlowestspellrange',['GetLowestSpellRange',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#aa9983ce6128169169a1b4d95f01839c5',1,'EloBuddy::SDK::Extensions']]],
  ['getprediction',['GetPrediction',['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_health.html#ad58289408aed051ef6afa79422e3d72a',1,'EloBuddy.SDK.Prediction.Health.GetPrediction(Dictionary&lt; Obj_AI_Base, int &gt; minionsTime)'],['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_health.html#a0cbeab9c83eabf87b44bc96881fbd32d',1,'EloBuddy.SDK.Prediction.Health.GetPrediction(Obj_AI_Base target, int time)'],['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_position.html#a2c529d9ba4e57f66c012be6cd53c9182',1,'EloBuddy.SDK.Prediction.Position.GetPrediction()']]],
  ['getpredictionaoe',['GetPredictionAoe',['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_position.html#a05b30b4616a6a6a82180612b11f30786',1,'EloBuddy::SDK::Prediction::Position']]],
  ['getrealpath',['GetRealPath',['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_position.html#a2b603a234f08ad1913d1fb9ee0f2e785',1,'EloBuddy::SDK::Prediction::Position']]],
  ['getspelldatafromname',['GetSpellDataFromName',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#ad4639a33fe280063c24de830b8a49b69',1,'EloBuddy::SDK::Extensions']]],
  ['getspellslotfromname',['GetSpellSlotFromName',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#af2a05bd89ac1c2984f9bc9169b403234',1,'EloBuddy::SDK::Extensions']]],
  ['gettarget',['GetTarget',['../class_elo_buddy_1_1_s_d_k_1_1_orbwalker.html#a1fd5a06d7b0553a89f34ac3602a4df53',1,'EloBuddy.SDK.Orbwalker.GetTarget()'],['../class_elo_buddy_1_1_s_d_k_1_1_spell_1_1_spell_base.html#ae0e71f5f7afcc328c49cdae974e8d026',1,'EloBuddy.SDK.Spell.SpellBase.GetTarget()']]],
  ['getyasuowallcollision',['GetYasuoWallCollision',['../class_elo_buddy_1_1_s_d_k_1_1_prediction_1_1_position_1_1_collision.html#af7b435b3b3e749ee49803144dbe5510a',1,'EloBuddy::SDK::Prediction::Position::Collision']]],
  ['grassobject',['GrassObject',['../class_elo_buddy_1_1_grass_object.html',1,'EloBuddy']]],
  ['gridtoworld',['GridToWorld',['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#ab39ca52146194dbe2730af4d43028242',1,'EloBuddy.SDK.Extensions.GridToWorld(this Vector3 vector)'],['../class_elo_buddy_1_1_s_d_k_1_1_extensions.html#a69ebf11290ec8a841655d8aabaedf666',1,'EloBuddy.SDK.Extensions.GridToWorld(this Vector2 vector)']]]
];
